# Generated by Django 5.1.4 on 2025-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_message_tag_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
