# Generated by Django 5.1.4 on 2025-01-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pollresponse_correct_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('host_email', models.EmailField(max_length=254)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('meeting_id', models.CharField(max_length=255)),
                ('join_url', models.URLField()),
                ('start_url', models.URLField()),
            ],
        ),
    ]
